Feature/eb basic styling
elisebeall/rancidtomatillos pull request #20
Opened 2021-12-05 22:39 UTC by elisebeall

## [Rancid Tomatillos]

[x] - Feature PR [🧩]
[ ] - Refactor PR [⚙️]
[ ] - BugFix PR [🐞]
[X] - User Interface PR [🖍]
[ ] - Error Handling PR [⚠️]
[ ] - Testing PR [🧑‍💻]

**What (if any) features are you implementing?**

 - For this pull request, the focus was on displaying mock data in a logical fashion on two different pages, as well as creating a navigable page for the user. This merge will close the following issues:
 - #2 
 - #5 
 - #7 
 - #8 
 - #12
 - #15

**What (if anything) did you refactor?**

 - (NA)

**Were there any issues that arose?**

 - (NA)

**Is there anything needs to be prioritized/errors to be addressed?**

 - (NA)

**Goals? Next steps?**

 - For the user interface, the goal will be to refine the styling by including padding and margins.  Adding icons & styling to buttons and containers.  
 - To add more features & functionality, the next steps will be to implement the API fetch calls to bring in more data.  This will give us endpoints for each of the individual movies, as well as background images & trailers.

<img width="1080" alt="screen shot of home page" src="https://user-images.githubusercontent.com/724355/144766694-e991a4ce-eedc-4597-afca-bd17143c976b.png">

<img width="1080" alt="screen shot of movie details" src="https://user-images.githubusercontent.com/724355/144766698-6b9979d8-ea2b-432c-b23d-1ae79d790460.png">

2021-12-06 16:02 UTC, elisebeall commented
@kaylagordon @CassandraGoose

2021-12-06 20:38 UTC, annamkummer requested changes
Please remove commented out sections, thanks!

2021-12-06 20:38 UTC, annamkummer commented on src/index.css
> +/* @import url('https://fonts.googleapis.com/css2?family=Raleway:ital,wght@1,300&display=swap'); */
Can these comments be removed?

2021-12-06 20:38 UTC, annamkummer commented on src/css/Poster.css
> +img:hover {
I really like this feature!

2021-12-06 20:57 UTC, merged

2021-12-06 21:03 UTC, elisebeall commented
Closes #2

2021-12-06 21:04 UTC, elisebeall reviewed
Changes made!

2021-12-06 21:07 UTC, elisebeall reviewed
Closes #5
Closes #7 
Closes #15

2021-12-06 21:07 UTC, elisebeall commented on PULL_REQUEST_TEMPLATE.md
> -## [name of project]
This is actually just a test comment.  Please pretend that you never even saw it.

2021-12-06 21:13 UTC, annamkummer reviewed
Remove comment?

2021-12-06 21:13 UTC, annamkummer commented on src/components/App.js
> +// import { render } from '@testing-library/react';
Can we remove this comment?

2021-12-07 22:39 UTC, kaylagordon reviewed
Looks great so far! I only had minor comments. My biggest feedback is that this is A LOT of code changes for one PR. I would consider this to be enough changes/features to be 3+ PRs. Consider pushing more often!

2021-12-07 22:39 UTC, kaylagordon commented on src/components/App.js
> +      showAllMovies: true,
You'll be able to cut this once Router is implemented

2021-12-07 22:39 UTC, kaylagordon commented on src/components/Poster.js
> +const Poster = (props) => {
Consider destructuring your props so you don't have to write `props.` so many times

2021-12-07 23:37 UTC, elisebeall commented
> Looks great so far! I only had minor comments. My biggest feedback is that this is A LOT of code changes for one PR. I would consider this to be enough changes/features to be 3+ PRs. Consider pushing more often!

Thanks @kaylagordon!

It _was_ a big pull request, but we specifically wanted to wait to merge with main until we had something that we felt showed all of the basic pieces.  @annamkummer created a branch for our original component architecture, and another for the movie details page.  I created a branch for styling.  From inside my styling branches, I would pull down Anna's branches and **attempt** to make them look pretty!  We definitely could have done it in smaller steps, but then main would've been something not ready for viewing.  Does that make sense?  I'd never been good about sticking to it in the past, but my understanding is, the main branch should be 'production ready'.

Thanks again for the code review! 🥰